### ISSUE TITLE
Have you been using this successfully & is sh script needed?

### ISSUE THREAD

**Issue by ahundt** [jhollowayj/tensorflow_slurm_manager#1]
Hey, Just wanted to check if you've been making use of this, and if an sh script is needed to configure the resource request.

**Comment by jhollowayj** [comment]
Hi!  So, I was doing research at a university who supplied the slurm cluster, and no longer have access to it since graduating.  I haven't used this script since.

**Comment by jhollowayj** [comment]
So, I believe it was working just fine on our cluster.  I don't have my research code set on hand, but can check in a few hours after I get home from work if you'd like.

Reading through the code, I believe you can do something like `SlurmClusterManager(num_param_servers=2, num_workers=4, startingPort=12345).build_cluster_spec()` to return the tuple of `cluster_spec, job, task_id` where those are what you pass into the tf.train.ClusterSpec (https://www.tensorflow.org/deploy/distributed).  `job` should be `worker` or `ps`, and `task_id` is the task... id... 

 Note, that each slurm node that you have been given *should* get an unique job+task_id combination.  

To test this script, I would just fire up a few simple slurm job, and have it assign 2 ps and 4 workers that just print out the results of this function to verify it is working as expected.  Try it on 4 slurm nodes, on 2 slurm nodes, on 6 slurm nodes, etc.  Then just read the output and see if it makes sense.

I really should have included a working example, but I was rushed for time at the end of my semester.  :)

Let me know if you need more help with that.  I'll do what I can, but not having a slurm cluster available anymore limits me just a little.

**Comment by jhollowayj** [comment]
Additionally, I wrote this against TF v0.8 or so... Not sure if the api has changed much.

**Comment by ahundt** [comment]
Cool thanks! Even so this should save me time. I have a SLURM cluster too so I'll give this a try & let you know if I have other questions.

**Comment by jhollowayj** [comment]
I'm glad I could help.  Let me know how it goes!

**Comment by jhollowayj** [comment]
FYI, I updated some of the comments and the readme.  Hopefully that helps a little.

**Comment by ahundt** [comment]
Thanks, is there any example code that uses the class? I just read through it and it looks like it returns an instance of the `ClusterSpec` class but I'm not familiar with usage. 

Maybe there could be a simple mnist example or something? 

perhaps based on https://www.tensorflow.org/deploy/distributed

**Comment by ahundt** [comment]
Also are you aware of a way to check if slurm is available first? With a simple function like that I could have my tensoflow python training script run in a local configuration or cluster configuration depending on if slurm is available.

**Comment by jhollowayj** [comment]
This should allow you to debug.  Have slurm run this file.
``` {python}
import slurm_cluster_manager as slm

dictionary, myjob, mytaskid = slm.SlurmClusterManager().build_cluster_spec()
print("++++++++++++++++")
print("CLUSERT SPEC: {}".format(dictionary))
print("\nMyRole: {} [{}]".format(myjob, mytaskid))
print("----------------\n\n")
```

-----
__Edit:__
you may have to change
`cluster_spec = tf.train.ClusterSpec({'worker': wk_strings, 'ps': ps_strings})` 
to
`cluster_spec = {'worker': wk_strings, 'ps': ps_strings}`

**Comment by jhollowayj** [comment]
I'll have to go through my old code tonight to get you more of an example in a real project.

**Comment by jhollowayj** [comment]
Also, I'm not sure what you mean by 
> check if slurm is available first?

If you mean, having each node wait until all the others are up and running, I believe that somethink like this takes care of all of that for you.

``` {python}
if FLAGS.job_name == "ps":
    server.join()
elif FLAGS.job_name == "worker":
    ....
    with tf.train.MonitoredTrainingSession(master=server.target,
                                           is_chief=(FLAGS.task_index == 0),
                                           checkpoint_dir="/tmp/train_logs",
                                           hooks=hooks) as mon_sess:
    ....
        while not mon_sess.should_stop():
            ...
            mon_sess.run(train_op)
```

**Comment by jhollowayj** [comment]
As for checking if you are running a local vs a distributed tensorflow setup, I don't think I did have a good answer for that.  The best way I could come up with was to just have an if statement switch off of a command line flag.  Perhaps someone else has addressed the issue.  Either way, it should be too bad if you set it up right...

**Comment by ahundt** [comment]
I mean sometimes I hope to just run on a local machine, so I'd like to have a single script detect if slurm is available or not, then run the local version if it is not available. I guess I can just use a python flag and run the slurm sh script accordingly.

**Comment by jhollowayj** [comment]
yeah, that's kinda how I set it up.  
One thing that I added to the slurm script was a git pull to get the latest and greatest.

**Comment by jhollowayj** [comment]
Ok, so I got my old code out, and I was looking through my git history, and I don't see a working state with the slurm set-up.  However, I did have a few lab machines that I would run a distributed setup, so splicing those two together should be good enough.

So, I'm going to upload the code as is, create a new branch, make the changes, and then post a link here.  It's messy and probably will be more confusing than helpful, but you should be able to rip out the parts you need.

**Comment by jhollowayj** [comment]
ok, **old code can be found [here](https://github.com/jhollowayj/distributed_tensorflow/blob/slurm_distributed/main.py)**.  [Lines 63-71 ](https://github.com/jhollowayj/distributed_tensorflow/blob/slurm_distributed/main.py#L63-71) are the important ones for integrating the slurm cluster manager script: 

``` {python}
# Create a cluster from the parameter server and worker hosts.
cluster, myjob, mytaskid = slm.SlurmClusterManager().build_cluster_spec()

# Create and start a server for the local task.
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.1, allow_growth=True)
server = tf.train.Server(cluster,
                        job_name=myjob,
                        task_index=mytaskid)
```

Don't for get to add `import slurm_cluster_manager as slm` at the top.  If they are in the same folder, this should work to import `slm` into your file.

-----

The rest of this code here is just the regular distributed stuff, in case you needed that.
Next part is pretty standard...
```{python}
if self.FLAGS.job_name == "ps":
    server.join()
elif self.FLAGS.job_name == "worker":
    # Do stuff
```

I used a supervisor, but I bet the TF API has changed since then... 
``` {python} 
# Create a "supervisor", which oversees the training process.
print "=============== building supervisor "
sv = tf.train.Supervisor(is_chief=(self.FLAGS.task_index == 0),
                        logdir="/mnt/labdrive/projects/distTF/modularDNN_Practice/logs/",
                        init_op=tf.initialize_all_variables(),
                        # summary_op=summary_op,
                        # saver=saver,
                        global_step=global_step_var)
```

Then I needed this part:
```
with sv.prepare_or_wait_for_session(server.target) as sess:
    # Application specific code.  Here I set up experience database for game replay, etc
    while not sv.should_stop() and not done_training:
        # Take a training step, update params, etc.

    # Once done, ask for all the services to stop.
sv.stop()
```

**Comment by jhollowayj** [comment]
One last note:  Completely separate from getting the slurm manager working...  I was having tensorflow learn how to play a simple maze game.  I found that having to sync every step in that maze game caused it to be unbearably slow (grabbing the weights from the ps, computing the expected value, updating the weights, send them back, repeat).  What I ended up doing is having two tf graphs that were copies of each other.  Workers would all have their own local copy that they would compute with, but they would also have a global copy that lived on the parameter servers.  

Every few seconds or so, they would compute the difference in their local network (since their last sync), and send that up to the `ps`.  Then they would grab the `ps` and overwrite their local copy.  This would be their new set of weights they would continue to train with, and would then repeate this process after another few seconds.  

There was a little danger in working with old, outdated copies of the weights, but the speed improvement was soo much bigger, I wasn't worried in the least.  It seemed to be stable enough for what I was doing.  Just an idea, if you find there is a lot of overhead in communication with the `ps`'s

**Comment by ahundt** [comment]
@jhollowayj thanks for the feedback! That sounds like a good strategy, and also I believe that is much like how papers like [Asynchronous Methods for Deep Reinforcement Learning](https://arxiv.org/pdf/1602.01783.pdf) do things.

Could you remind me what `ps` is?

**Comment by jhollowayj** [comment]
`ps` is `parameter server`, as opposed to `worker`

**Comment by ackdav** [comment]
hi @ahundt and @jhollowayj,
@jhollowayj any way you could post a full working script? I imported slurm_manager, but coming from "normal"/local tensorflow it's a bit overwhelming to get all variables & tasks right to run in a distributed fashion

**Comment by jhollowayj** [comment]
@derdav3 I didn't finish one before I graduated, and I no longer have a cluster.  Perhaps @ahundt could post one if he gets it working, but that's kinda up to him.  :)

As far as getting all the variables and tasks right, it can be overwhelming.  And there are a lot of ways to split the work up amongst the different computers.  Do you mind me asking what kind of setup are you running?

**Comment by ackdav** [comment]
@jhollowayj We have a Debian cpu-slurm-cluster at our uni. I'd like to push through some configurations (different # of hidden layers / different optimizer etc) of an NN to see how the performance compares. 

A few beginner questions:
1. Do we still need to start the program in this fashion "python example.py --job-name="ps" --task_index=0" with your slurm_manager? doesn't it essentially distribute the jobs itself? 
2. I inserted these lines:
`# Create a cluster from the parameter server and worker hosts.
cluster, myjob, mytaskid = slm.SlurmClusterManager().build_cluster_spec()`

`# Create and start a server for the local task.
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.1, allow_growth=True)
server = tf.train.Server(cluster,
                        job_name=myjob,
                        task_index=mytaskid)`

which gives following output with a 3-node job:
`I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:200] Initialize GrpcChannelCache for job ps -> {0 -> localhost:2222}
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:200] Initialize GrpcChannelCache for job worker -> {0 -> claudio06:2222, 1 -> claudio08:2222}
I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:221] Started server with target: grpc://localhost:2222
`
why is a localhost involved here? Is this just slurm behaviour?
As you can see - I'm new to slurm and fairly new to tensorflow... not the best combination :) thx for your help!

**Comment by jhollowayj** [comment]
Well, this probably isn't the best place to answer as it almost deserves a questions on stack overflow or some other QA site, but I'll give you an answer here none the less.

## Background
Slurm will give you 3 computers in the case you give above.  You can do whatever you want with these three computers.  It looks like you chose to have 1 ps, and 2 workers.  

Now for tensorflow's distributed setup, you need to know which three computers are to be used.  Because slurm will give you whichever computers are available, you don't really know which ones they are going to be ahead of time, which makes building the TF.cluster_spec kinda hard.  `Enter: SlurmClusterManager`.  Slurm sets up that information for you in the Environment Variables.  Great.  You now have a list of computers.  Now you have to use that to build a Cluster Spec.

In a few seconds, your computers are going to start talking to each other, and they all have to know who is doing what.  The cluster spec definition has to be consistent across all computers.

Above you have the output of one computer, your ps.  (I'm going to say that he was on `claudio04` but there is really no way for me to know what the actual hostname was and it doesn't actually matter.)  For distributed TF, you build the cluster spec from a map/dictionary, something like this: 
>'ps':'claudio4:2222', 'worker':'claudio6:2222, claudio8:2222'
Each computer is defined by a dns name/ip address followed by a :port.  (By having the port number, you can have multiple TF workers/ps's on a single node.  They would just share resources, but the communication between those multiple instances is really fast!)
At run time, each computer knows who they are in this list of workers via the SlurmClusterManager's output of `myjob` and `mytaskid`.  ps:0 would be `claudio4:2222`, worker:1 would be `claudio8:2222`.  TF will then translate their hostname from `claudio4` to `localhost`.  localhost just means local... host; themselves.  Google that for more info if needed.

Ok, that should be enough background now...  back to your questions 

## Answers
1. No.  Before you had to launch it on 3 computers with

> (on claudio4) `python example.py --job-name="ps" --task_index=0`
> (on claudio6) `python example.py --job-name="worker" --task_index=0`
> (on claudio8) `python example.py --job-name="worker" --task_index=1`

However, you would still need to let them know what your cluster would look like, so each one would also have to add the string:

>`--param-server-list="claudio4:2222" --worker-list="claudio6:2222,claudio8:2222"`

which makes your commands now:

> (on claudio4) `python example.py --param-server-list="claudio4:2222" --worker-list="claudio6:2222,claudio8:2222" --job-name="ps" --task_index=0`

> (on claudio6) `python example.py --param-server-list="claudio4:2222" --worker-list="claudio6:2222,claudio8:2222" --job-name="worker" --task_index=0`

> (on claudio8) `python example.py --param-server-list="claudio4:2222" --worker-list="claudio6:2222,claudio8:2222" --job-name="worker" --task_index=1`

Kinda gross to work with, right?  And what happens when you can't use claudio8 and have to use claudio10?  Well, you have to change the command on all computers...

**SlurmClusterManager takes care of that for you.  You just have to run `python SCM_example.py` and it builds those arguments for your.**

-----

2. Tensorflow is the one who brings localhost into the picture.  Because each computer is given the flag `task_index` (and `job-name`), they know who they are in the cluster spec.  They simply ignore what the actual hostname was in that position and replace it with `localhost`.  So the cluster spec can not reuse computers, and the order has to be the same on every computer because of this.

If you had switched the order on claudio8 to be 

> `python example.py --param-server-list="claudio4:2222" --worker-list="claudio**8**:2222,claudio**6**:2222" --job-name="worker" --task_index=1`

Claudio8 would think that he is claudio6, and would think that claudio6 was claudio8.  When it was time for him to talk with the other worker computer, he would then contact claudio8:2222 (himself), instead of claudio6:2222 like he is supposed to.

-----
That's a long winded answer, but hopefully it helps. :)  I'd suggest reading a few tutorials:

https://www.tensorflow.org/deploy/distributed
http://ischlag.github.io/2016/06/12/async-distributed-tensorflow/

Once you understand those, come back to slurm, and know that SCM will simply build the cluster spec for you.  SCM is a really simple puzzle piece once you understand Distributed TF.

**Comment by ackdav** [comment]
wow! thanks a ton for this! really clears up some question marks...

**Comment by ackdav** [comment]
@jhollowayj After reading a bunch and watching the google dev videos I think I understand the principle behind it (thanks!). However, I couldn't figure out why the whole thing doesn't start up... 

I opened a stackoverflow: http://stackoverflow.com/questions/42889089/distributed-tf-seems-frozen-basic-example

my slurm script looks like:
```
#!/bin/sh
#SBATCH --job-name="tensorflow"
#SBATCH -N 3
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=23
#SBATCH --partition=kraken_fast
#SBATCH -t 0-07:00:00
#SBATCH --output=arrayJob_%A_%a.out
#SBATCH --error=arrayJob_%A_%a.err

cd ~/directory
python tensorflow.py
```

Any ideas? 😅
